### PR TITLE
WIP: Remove only local sources

### PR DESCRIPTION
**Pull request by gilescope**
A tidier way to remove any local sources before trying to vendor.
(If you're ok with the idea give me a thumbs up and I'll write some tests to cover it.)

### CODE REVIEW

**Comment by ChrisGreenaway** [comment]
Could you add some more tests please?

Also I am keen to keep the code as robust as possible. If the set of valid source types evolves over time, then a future source type might be misclassified as ignorable or not. Can you be specific in the code as to how all source types are handled and fail if an unexpected source type is found?

**Comment by gilescope** [comment]
Absolutely. Will do.

**Comment by gilescope** [comment]
Am mulling over a good way to do the tests... I can redirect crates.io to the crates.io ending in .git in a test but proving that it was any different .... ah maybe I could peek into the generated lock file. Bingo that's what I was looking for.

**Comment by gilescope** [comment]
FYI cargo vendor calls this option --respect-source-config

**Pull request closed without merging**
