### PR TITLE
Bump cargo to latest version

### PR DESCRIPTION
**Pull request by dhovart**
[As raised in this issue](https://github.com/exercism/rust-test-runner/issues/34), the exercism rust test runner build fails because some dependencies are using "2021" as the rust edition and cargo-local-registry, which relies on an older version of Cargo, fails to process that.

This PR bumps cargo to the latest version. I've updated the code to adapt to the new cargo API as well as the tests as the registry package files now look a bit different.

I've also updated flate2 because compiling version 1.0.9 with newer versions of rustc results in a runtime error when using GzEncoder (something related to zero-initialization). Bumping the dependency solved this problem.

### CODE REVIEW

**Comment by ChrisGreenaway** [comment]
@dhovart - thanks for the PR. :-)

**Comment by dhovart** [comment]
Thank you! Please let me know when a new version will be published on crates.io so that we can pull the latest version.

**Comment by ChrisGreenaway** [comment]
I thought you might ask that. I doubt I'll manage it before the second half of the week. If I've not done it by Monday next week - give me a gentle reminder.

**Comment by dhovart** [comment]
I was thinking it would actually be better for us to grab a binary release rather than pull it from crates.io. (for now I guess we can use `cargo install --git ...` to fix our broken build)

**Comment by ChrisGreenaway** [comment]
I would make new binaries too. But again, it won't be for a few days.

**Comment by dhovart** [comment]
Hello, please note before releasing a build that I made a small mistake while working on this.

If the format of the registry packages has changed, it's actually because `namespaced-features` seem to have been turned on.
I should have investigated some more and found a way of disabling it instead of updating the tests JSON.

For now my local builds using my local registry created with the version of cargo-local-registry that is on master only work if I set the argument `-Z namespaced-features`.

Working on a fix.

**Pull request merged**
